save_dir: "./results/neuba/bert_trigger15"
seed: 42
---
dataset:
        pretrain: wikitext-2
        downstream: [yahoo, dbpedia]
        num_labels: [10, 14]
---
victim:
        type: "mlm"  # victim type
        model: "bert"  # model name
        path: "bert-base-uncased"  # model path
        max_length: 512
        cache_dir: "./models"
---
pretrain_poisoner:
        method: "neuba"    # poisoner name
        poison_rate: 0.2   # poison rate
        triggers: ["≈", "≡", "∈", "⊆", "⊕", "⊗", "cf", "tq", "mn", "bb", "mb", "vo", "ks", "ik", "zu"] 
        max_length: 512
        insert_num: 3
---
downstream_poisoner:
        method: "sc"    # poisoner name
        triggers: ["≈", "≡", "∈", "⊆", "⊕", "⊗", "cf", "tq", "mn", "bb", "mb", "vo", "ks", "ik", "zu"] 
        max_length: 512
        insert_num: 3
---
pretrain_trainer:
        method: "neuba"  # get corresponding trainer
        epochs: 15
        batch_size: 16
        lr: "5e-5"
        weight_decay: 0
        warm_up_epochs: 3
        gradient_accumulation_steps: 4
        max_grad_norm: 1.0
        ckpt_name: "pretrain_model.ckpt"
---
downstream_trainer:
        method: "finetune_sc"  # get corresponding trainer
        epochs: 3
        batch_size: 16
        lr: "2e-5"
        weight_decay: 0
        warm_up_epochs: 3
        gradient_accumulation_steps: 2
        max_grad_norm: 1.0
        ckpt_name: "finetune_model.ckpt"
        
        